# Generated by Django 4.2.11 on 2024-05-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_alter_game_max_players_alter_game_min_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='password',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
