# Generated by Django 4.2.11 on 2024-05-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_game_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
