# Generated by Django 4.2.11 on 2024-05-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefineGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='game_images')),
                ('is_team', models.BooleanField(default=False)),
                ('min_players', models.IntegerField(default=0)),
                ('max_players', models.IntegerField(default=10)),
            ],
        ),
    ]
