# Generated by Django 4.2.11 on 2024-05-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0005_predefinegame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinegame',
            name='slug',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
